# Generated by Django 5.2.4 on 2025-08-03 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Název')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Název barvy')),
                ('hex_code', models.CharField(blank=True, help_text='#RRGGBB', max_length=7, verbose_name='HEX kód')),
            ],
            options={
                'verbose_name': 'Barva',
                'verbose_name_plural': 'Barvy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Název')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='URL (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena (Kč)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['name'],
            },
        ),
    ]
