# Generated by Django 5.2.4 on 2025-08-03 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Upraveno'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Obrázek')),
                ('alt_text', models.CharField(blank=True, max_length=160, verbose_name='ALT text')),
                ('is_main', models.BooleanField(default=False, verbose_name='Hlavní obrázek')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Nahráno')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Obrázek produktu',
                'verbose_name_plural': 'Obrázky produktů',
                'ordering': ['product', 'ordering', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_cm', models.PositiveIntegerField(default=60, verbose_name='Délka (cm)')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Když prázdné, použije se cena produktu', max_digits=10, null=True, verbose_name='Cena variace (Kč)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Sklad (ks)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color', verbose_name='Barva')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Varianta',
                'verbose_name_plural': 'Varianty',
                'ordering': ['product', 'ordering', 'color__name', 'length_cm'],
                'constraints': [models.UniqueConstraint(fields=('product', 'color', 'length_cm'), name='uniq_product_color_length')],
            },
        ),
    ]
