# Generated by Django 5.2.4 on 2025-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(choices=[('czp_balikovna', 'Česká pošta – Balíkovna'), ('czp', 'Česká pošta (ostatní)'), ('other', 'Jiný dopravce')], default='czp_balikovna', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
